### ISSUE TITLE
Deleting django_content_type between fixtures causes kitsune tests to fail

### ISSUE THREAD

**Issue by pcraciunoiu** [jbalogh/test-utils#2]
[This is probably not the best fix.](http://paulc.pastebin.mozilla.org/777216)

Maybe we can talk about it in person on Monday?

It appears that the `django_content_type` table isn't repopulated for every test or test case, which is causing problems.

[Relevant bug](https://bugzilla.mozilla.org/show_bug.cgi?id=590004)  -- see stack trace in [comment 1](https://bugzilla.mozilla.org/show_bug.cgi?id=590004#c1)

**Comment by erikrose** [comment]
The new TestCase in 4300764d9dcb05487a33127760bc3d658369b97d is smarter about what to truncate and never clears django_content_type to begin with.
